// src/lib/components/panels/CommandPalette.svelte
<script lang="ts">
  import Modal from '../common/Modal.svelte';
  import { paletteStore, type PaletteItem } from '../../stores/palette';
  import { 
    FileText, Command as CmdIcon, CircleDot, Clock
  } from 'lucide-svelte';

  let { isOpen, onClose, initialQuery = '' }: { isOpen: boolean; onClose: () => void; initialQuery?: string } = $props();

  let query = $state('');
  let selectedIndex = $state(0);
  let inputEl: HTMLInputElement | undefined = $state();
  
  let filteredItems = $derived.by(() => {
    if (!$paletteStore.isLoaded) return [];
    
    let isCommandMode = query.startsWith('>');
    let actualQuery = isCommandMode ? query.slice(1).trim() : query.trim();

    let pool = $paletteStore.items.filter((i: any) => isCommandMode ? i.category === 'command' : i.category !== 'command');

    if (!actualQuery) return pool.slice(0, 15);
    if (!$paletteStore.fzfInstance) return [];

    const results = $paletteStore.fzfInstance.find(actualQuery);
    return results
      .map((r: any) => r.item)
      .filter((item: any) => isCommandMode ? item.category === 'command' : item.category !== 'command');
  });

  function handleSelect(item: PaletteItem) {
    item.action();
    onClose();
  }

  function handleKeydown(e: KeyboardEvent) {
    if (!isOpen) return;
    // Escape is handled by Modal, but let's keep arrow keys and enter
    if (e.key === 'ArrowDown') { e.preventDefault(); selectedIndex = (selectedIndex + 1) % filteredItems.length; }
    if (e.key === 'ArrowUp') { e.preventDefault(); selectedIndex = (selectedIndex - 1 + filteredItems.length) % filteredItems.length; }
    if (e.key === 'Enter') { e.preventDefault(); if (filteredItems[selectedIndex]) handleSelect(filteredItems[selectedIndex]); }
  }

  $effect(() => {
    if (isOpen) {
      query = initialQuery;
      selectedIndex = 0;
      requestAnimationFrame(() => inputEl?.focus());
    }
  });

  function getIcon(category: string) {
    switch (category) {
      case 'file': return FileText;
      case 'symbol': return CircleDot;
      case 'recent': return Clock;
      default: return CmdIcon;
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

<Modal {isOpen} title="Command Palette" widthClass="max-w-xl" {onClose}>
  {#snippet children()}
    <div class="flex flex-col h-full">
      <div class="flex items-center px-4 py-3 border-b border-subtle shrink-0">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-icon-default shrink-0"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
        <input
          bind:this={inputEl}
          class="flex-1 bg-transparent border-none outline-none px-3 text-sm text-primary placeholder-muted"
          placeholder="Type a command or search..."
          bind:value={query}
          oninput={() => selectedIndex = 0}
        />
      </div>
      <div class="h-[460px] overflow-y-auto py-2 scrollbar-hide flex flex-col">
        {#if !$paletteStore.isLoaded}
          <div class="px-4 py-3 text-sm text-center text-muted flex-1 flex items-center justify-center">
            <span class="flex items-center gap-2">
              <span class="inline-block w-3 h-3 rounded-full border-2 border-muted border-t-transparent animate-spin"></span>
              Loading workspace files...
            </span>
          </div>
        {:else if filteredItems.length === 0}
          <div class="px-4 py-3 text-sm text-center text-muted flex-1 flex items-center justify-center">No items found</div>
        {:else}
          {#each filteredItems as cmd, i (cmd.id)}
            {@const Icon = getIcon(cmd.category)}
            <div
              role="option"
              tabindex="0"
              aria-selected={i === selectedIndex}
              class="flex items-center justify-between px-4 py-2 cursor-pointer transition-colors"
              class:bg-selected={i === selectedIndex}
              class:text-primary={i === selectedIndex}
              class:text-secondary={i !== selectedIndex}
              onclick={() => handleSelect(cmd)}
              onkeydown={(e) => { if (e.key === 'Enter') handleSelect(cmd); }}
              onmouseenter={() => selectedIndex = i}
            >
              <div class="flex items-center gap-3 overflow-hidden">
                <span class="text-muted shrink-0">
                  <Icon size={14} />
                </span>
                <div class="flex flex-col truncate">
                  <span class="text-sm truncate">{cmd.label}</span>
                  {#if cmd.description}
                    <span class="text-[10px] text-muted truncate">{cmd.description}</span>
                  {/if}
                </div>
              </div>
              {#if cmd.shortcut}
                  <kbd class="text-xs px-2 py-0.5 rounded bg-surface-2 text-muted shrink-0">{cmd.shortcut}</kbd>
              {/if}
            </div>
          {/each}
        {/if}
      </div>
    </div>
  {/snippet}
</Modal>

<style>
  .scrollbar-hide::-webkit-scrollbar { display: none; }
  .scrollbar-hide { -ms-overflow-style: none; scrollbar-width: none; }
</style>

// src/components/CommandPalette.tsx
import { useState, useEffect, useRef } from 'react';
import { Search } from 'lucide-react';
import { useSettingsStore } from '../store/settingsStore';

interface Command {
  id: string;
  name: string;
  shortcut?: string;
  action: () => void;
}

interface CommandPaletteProps {
  isOpen: boolean;
  onClose: () => void;
  commands: Command[];
}

export default function CommandPalette({ isOpen, onClose, commands }: CommandPaletteProps) {
  const [query, setQuery] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const { settings } = useSettingsStore();
  const isDark = settings.theme === 'dark' || (settings.theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);

  const filteredCommands = commands.filter(c => 
    c.name.toLowerCase().includes(query.toLowerCase())
  );

  const handleSelect = (cmd: Command) => {
    cmd.action();
    onClose();
  };

  useEffect(() => {
    if (isOpen) {
      setQuery('');
      setSelectedIndex(0);
      setTimeout(() => inputRef.current?.focus(), 10);
    }
  }, [isOpen]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        onClose();
      } else if (e.key === 'ArrowDown') {
        e.preventDefault();
        setSelectedIndex(prev => (prev + 1) % filteredCommands.length);
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setSelectedIndex(prev => (prev - 1 + filteredCommands.length) % filteredCommands.length);
      } else if (e.key === 'Enter') {
        e.preventDefault();
        if (filteredCommands[selectedIndex]) {
          handleSelect(filteredCommands[selectedIndex]);
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, filteredCommands, selectedIndex, onClose]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[10vh] bg-black/50 backdrop-blur-sm" onClick={onClose}>
      <div 
        className={`w-full max-w-lg rounded-xl shadow-2xl overflow-hidden border ${isDark ? 'bg-zinc-900 border-zinc-700' : 'bg-white border-zinc-200'}`}
        onClick={e => e.stopPropagation()}
      >
        <div className={`flex items-center px-4 py-3 border-b ${isDark ? 'border-zinc-800' : 'border-zinc-200'}`}>
          <Search size={18} className={isDark ? 'text-zinc-500' : 'text-zinc-400'} />
          <input
            ref={inputRef}
            className={`flex-1 bg-transparent border-none outline-none px-3 text-sm ${isDark ? 'text-zinc-100 placeholder:text-zinc-500' : 'text-zinc-900 placeholder:text-zinc-400'}`}
            placeholder="Type a command or search..."
            value={query}
            onChange={e => {
              setQuery(e.target.value);
              setSelectedIndex(0);
            }}
          />
        </div>
        
        <div className="max-h-80 overflow-y-auto py-2">
          {filteredCommands.length === 0 ? (
            <div className={`px-4 py-3 text-sm text-center ${isDark ? 'text-zinc-500' : 'text-zinc-400'}`}>
              No commands found
            </div>
          ) : (
            filteredCommands.map((cmd, i) => (
              <div 
                key={cmd.id}
                className={`flex items-center justify-between px-4 py-2 cursor-pointer ${
                  i === selectedIndex 
                    ? (isDark ? 'bg-blue-600 text-white' : 'bg-blue-500 text-white') 
                    : (isDark ? 'text-zinc-300 hover:bg-zinc-800' : 'text-zinc-700 hover:bg-zinc-100')
                }`}
                onClick={() => handleSelect(cmd)}
                onMouseEnter={() => setSelectedIndex(i)}
              >
                <span className="text-sm">{cmd.name}</span>
                {cmd.shortcut && (
                  <kbd className={`text-xs px-2 py-0.5 rounded ${
                    i === selectedIndex 
                      ? (isDark ? 'bg-blue-500 text-blue-100' : 'bg-blue-600 text-blue-50')
                      : (isDark ? 'bg-zinc-800 text-zinc-500' : 'bg-zinc-200 text-zinc-500')
                  }`}>
                    {cmd.shortcut}
                  </kbd>
                )}
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
