// src/lib/components/SearchPanel.svelte
<script lang="ts">
    import { uiStore } from '../stores/ui';
  import { editorStore } from '../stores/editor';
  import { invoke } from '@tauri-apps/api/core';
  import { 
    Replace, ChevronDown, ChevronRight, X, 
    File, FileCode, FileJson, FileText, Image, Settings, Globe, Hash, Loader2 
  } from 'lucide-svelte';

  const ICON_MAP: Record<string, any> = {
    ts: FileCode, tsx: FileCode, js: FileCode, jsx: FileCode,
    rs: FileCode, py: FileCode, go: FileCode,
    html: Globe, css: Hash, json: FileJson,
    md: FileText, svg: Image, png: Image, jpg: Image,
    toml: Settings, yaml: Settings, yml: Settings,
  };

  interface SearchResult { path: string; line: number; text: string; }



  let isReplaceVisible = $state(false);
  let searchQuery = $state('');
  let replaceQuery = $state('');
  let results = $state<SearchResult[]>([]);
  let isSearching = $state(false);
  let filesScanned = $state(0);
  let matchesFound = $state(0);
  const ui = uiStore;

  let debounceTimer: number | undefined;
  let searchVersion = 0;

  // Debounced search with streaming 
  $effect(() => {
    clearTimeout(debounceTimer);
    if (searchQuery.trim().length > 0 && $ui.explorerRoot) {
      debounceTimer = setTimeout(performSearch, 500);
    } else {
      results = [];
      filesScanned = 0;
      matchesFound = 0;
    }
    return () => clearTimeout(debounceTimer);
  });

  async function performSearch() {
    const currentVersion = ++searchVersion;
    if (isSearching) {
      try { await invoke('cancel_search'); } catch {}
    }
    isSearching = true;
    results = [];
    filesScanned = 0;
    matchesFound = 0;

    await uiStore.withStatus(`Searching workspace...`, async () => {
      try {
        let allResults: SearchResult[] = [];
        let batch = 0;

        // Streaming: receive results in batches every 20 matches or 50ms
        while (batch < 100) {
          if (currentVersion !== searchVersion) break;
          const res = await invoke<{ results: SearchResult[]; total_scanned: number }>('search_in_files_stream', {
            root: $ui.explorerRoot,
            pattern: searchQuery,
            batchSize: 20,
          });

          if (currentVersion !== searchVersion) break;
          if (res && res.results) {
            allResults = [...allResults, ...res.results];
            matchesFound = allResults.length;
            filesScanned = res.total_scanned || 0;

            // Update results incrementally for user feedback
            results = [...allResults];
          }

          if (!res || !res.results || res.results.length < 20) break;
          batch++;

          // Yield to UI thread every batch
          await new Promise(r => setTimeout(r, 0));
        }

        if (currentVersion === searchVersion) {
          results = allResults;
        }
      } catch (err) {
        if (currentVersion === searchVersion) {
          console.error(err);
          results = [];
        }
      } finally {
        if (currentVersion === searchVersion) {
          isSearching = false;
        }
      }
    }, 500);
  }

  function handleCancel() {
    invoke('cancel_search').catch(console.error);
    searchVersion++;
    isSearching = false;
  }

  async function handleResultClick(path: string) {
    try {
      const name = path.split(/[\/\\]/).pop() || 'Unknown';
      const isImage = /\.(png|jpe?g|gif|webp|svg|ico)$/i.test(name);
      let content: string | null = null;
      if (!isImage) {
        const result: any = await invoke('open_file', { path });
        content = result.content;
      }
      const language = isImage ? 'image' : await invoke<string>('detect_language', { path });
      editorStore.addTab({ id: path, path, name, content, language, isPreview: true });
    } catch (err) { console.error("Failed to open file from search", err); }
  }

  let groupedResults = $derived(
    results.reduce((acc, curr) => {
      if (!acc[curr.path]) acc[curr.path] = [];
      acc[curr.path].push(curr);
      return acc;
    }, {} as Record<string, SearchResult[]>)
  );
</script>

<div class="flex flex-col p-2 gap-2 h-full text-primary">
  <div class="flex flex-col gap-1.5 shrink-0">
    <div class="flex items-start gap-1">
      <button aria-label="Toggle replace" onclick={() => isReplaceVisible = !isReplaceVisible} class="mt-1 p-0.5 rounded cursor-pointer transition-colors hover:bg-hover">
        {#if isReplaceVisible}
          <ChevronDown size={16} />
        {:else}
          <ChevronRight size={16} />
        {/if}
      </button>
      <div class="flex flex-col flex-1 gap-1.5 min-w-0">
        <div class="flex items-center flex-1 border rounded px-1.5 py-1 border-subtle bg-canvas focus-within:border-focus">
          <input type="text" placeholder="Search" bind:value={searchQuery} class="flex-1 bg-transparent text-sm outline-none min-w-0 placeholder-muted" />
          {#if isSearching}
            <button aria-label="Cancel search" onclick={handleCancel} class="p-0.5 rounded cursor-pointer shrink-0 ml-1 text-icon-default hover:text-icon-active hover:bg-hover transition-colors">
              <X size={14} />
            </button>
          {/if}
        </div>
        {#if isReplaceVisible}
        <div class="flex items-center flex-1 border rounded px-1.5 py-1 border-subtle bg-canvas focus-within:border-focus">
            <input type="text" placeholder="Replace" bind:value={replaceQuery} class="flex-1 bg-transparent text-sm outline-none min-w-0 placeholder-muted" />
            <button aria-label="Replace All" class="ml-1 p-0.5 rounded cursor-pointer transition-colors shrink-0 text-icon-default hover:text-icon-active hover:bg-hover">
              <Replace size={14} />
            </button>
          </div>
        {/if}
      </div>
    </div>
  </div>
  <div class="flex-1 overflow-y-auto mt-2 text-sm">
    {#if isSearching}
      <div class="flex items-center gap-2 px-6 text-xs text-muted">
        <Loader2 size={12} class="animate-spin" />
        <span>Searching... {filesScanned} files scanned, {matchesFound} matches found</span>
        <button onclick={handleCancel} class="underline ml-2 transition-colors text-icon-default hover:text-icon-active">Cancel</button>
      </div>
    {:else if results.length > 0}
      <div class="text-xs px-6 pb-1 text-muted">{results.length} results in {Object.keys(groupedResults).length} files</div>
          <div class="flex flex-col mb-1">
            {#each Object.entries(groupedResults) as [path, pathResults] (path)}
              {@const Icon = ICON_MAP[path.split('.').pop()?.toLowerCase() || ''] || File}
              <div class="flex flex-col mb-1">
                <div class="flex items-center gap-1.5 px-2 py-1 cursor-pointer select-none group w-full overflow-hidden hover:bg-hover transition-colors" role="treeitem" tabindex="0" aria-selected={false} onclick={() => handleResultClick(path)} onkeydown={(e) => { if (e.key === 'Enter') handleResultClick(path); }}>
                  <span class="shrink-0 text-muted">
                    <ChevronDown size={14} />
                  </span>
                  <span class="shrink-0 text-accent">
                    <Icon size={14} />
                  </span>
                  <span class="text-xs truncate min-w-0 font-medium" title={path}>{path.split(/[\/\\]/).pop()}</span>
                  <span class="text-[10px] px-1 rounded-full shrink-0 bg-surface text-muted">{pathResults.length}</span>
                </div>
            <div class="flex flex-col">
              {#each pathResults as res, i (i)}
                <div class="flex items-start gap-2 pl-8 pr-2 py-0.5 cursor-pointer text-xs group text-secondary hover:text-primary hover:bg-hover transition-colors" role="option" tabindex="0" aria-selected={false} onclick={() => handleResultClick(path)} onkeydown={(e) => { if (e.key === 'Enter') handleResultClick(path); }} title={res.text.trim()}>
                  <span class="shrink-0 w-8 text-right select-none opacity-50 text-muted">{res.line}</span>
                  <span class="truncate flex-1 group-hover:text-primary font-mono text-[11px] mt-[1px]">
                    {res.text.trim()}
                  </span>
                </div>
              {/each}
            </div>
          </div>
        {/each}
      </div>
    {:else if searchQuery.length > 0}
      <div class="px-6 text-xs text-muted">No results found.</div>
    {:else}
      <div class="px-6 text-xs text-muted">Type to search across workspace.</div>
    {/if}
  </div>
</div>

// src/components/SearchPanel.tsx
import { useState, useEffect } from "react";
import { ChevronRight, ChevronDown, Replace as ReplaceIcon, File } from "lucide-react";
import { useSettingsStore } from "../store/settingsStore";
import { useUiStore } from "../store/uiStore";
import { useEditorStore } from "../store/editorStore";
import { invoke } from "@tauri-apps/api/core";

interface SearchResult {
  path: string;
  line: number;
  text: string;
}

export default function SearchPanel() {
  const { settings } = useSettingsStore();
  const isDark = settings.theme === 'dark' || (settings.theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
  
  const [isReplaceVisible, setIsReplaceVisible] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [replaceQuery, setReplaceQuery] = useState("");
  const [results, setResults] = useState<SearchResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);

  const { explorerRoot } = useUiStore();
  const { addTab } = useEditorStore();

  useEffect(() => {
    const handler = setTimeout(() => {
      if (searchQuery.trim().length > 0 && explorerRoot) {
        performSearch();
      } else {
        setResults([]);
      }
    }, 1000);

    return () => clearTimeout(handler);
  }, [searchQuery, explorerRoot]);

  const performSearch = async () => {
    setIsSearching(true);
    try {
      const res = await invoke<SearchResult[]>('search_in_files', { path: explorerRoot, query: searchQuery });
      setResults(res || []);
    } catch (err) {
      console.error(err);
      setResults([]);
    } finally {
      setIsSearching(false);
    }
  };

  const handleResultClick = async (path: string) => {
    try {
      const name = path.split(/[\/\\]/).pop() || 'Unknown';
      const isImage = /\.(png|jpe?g|gif|webp|svg|ico)$/i.test(name);
      let content = '';
      if (!isImage) {
        const result = await invoke<any>('open_file', { path });
        content = result.content;
      }
      
      let language = 'plaintext';
      if (!isImage) {
          language = await invoke<string>('detect_language', { path });
      }

      addTab({
        id: path,
        path: path,
        name: name,
        content,
        language: isImage ? 'image' : language,
        isPreview: true
      });
    } catch (err) {
      console.error("Failed to open file from search", err);
    }
  };

  // Group results by file path
  const groupedResults = results.reduce((acc, curr) => {
    if (!acc[curr.path]) acc[curr.path] = [];
    acc[curr.path].push(curr);
    return acc;
  }, {} as Record<string, SearchResult[]>);

  const renderHighlightedText = (text: string, query: string) => {
    if (!query) return text;
    const regex = new RegExp(`(${query.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')})`, 'gi');
    const parts = text.split(regex);
    
    return parts.map((part, i) => {
      if (part.toLowerCase() === query.toLowerCase()) {
        return (
          <span 
            key={i} 
            className={isDark ? "bg-orange-500/30 border border-orange-500/50 rounded-[2px]" : "bg-orange-500/20 border border-orange-500/40 rounded-[2px]"}
          >
            {part}
          </span>
        );
      }
      return <span key={i}>{part}</span>;
    });
  };

  return (
    <div className={`flex flex-col p-2 gap-2 h-full ${isDark ? 'text-zinc-300' : 'text-zinc-700'}`}>
      <div className="flex flex-col gap-1.5 shrink-0">
        <div className="flex items-start gap-1">
          <button 
            onClick={() => setIsReplaceVisible(!isReplaceVisible)}
            className={`mt-1 p-0.5 rounded cursor-pointer transition-colors ${isDark ? 'hover:bg-zinc-700' : 'hover:bg-zinc-300'}`}
          >
            {isReplaceVisible ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
          </button>
          
          <div className="flex flex-col flex-1 gap-1.5 min-w-0">
            <div className={`flex items-center flex-1 border rounded px-1.5 py-1 ${isDark ? 'border-zinc-700 bg-[#1e1e1e] focus-within:border-blue-500' : 'border-zinc-300 bg-white focus-within:border-blue-500'}`}>
              <input 
                type="text" 
                placeholder="Search" 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="flex-1 bg-transparent text-sm outline-none placeholder:text-zinc-500 min-w-0"
              />
            </div>

            {isReplaceVisible && (
              <div className={`flex items-center flex-1 border rounded px-1.5 py-1 ${isDark ? 'border-zinc-700 bg-[#1e1e1e] focus-within:border-blue-500' : 'border-zinc-300 bg-white focus-within:border-blue-500'}`}>
                <input 
                  type="text" 
                  placeholder="Replace" 
                  value={replaceQuery}
                  onChange={(e) => setReplaceQuery(e.target.value)}
                  className="flex-1 bg-transparent text-sm outline-none placeholder:text-zinc-500 min-w-0"
                />
                <button 
                  title="Replace All"
                  className={`ml-1 p-0.5 rounded cursor-pointer transition-colors shrink-0 ${isDark ? 'text-zinc-400 hover:text-white hover:bg-zinc-700' : 'text-zinc-500 hover:text-black hover:bg-zinc-200'}`}
                >
                  <ReplaceIcon size={14} />
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto mt-2 text-sm">
        {isSearching ? (
          <div className="px-6 text-xs text-zinc-500">Searching...</div>
        ) : results.length > 0 ? (
          <div className="flex flex-col">
            {Object.entries(groupedResults).map(([path, pathResults]) => {
              const fileName = path.split(/[\/\\]/).pop() || 'Unknown';
              // Calculate relative path for display if needed, but we can just show filename
              return (
                <div key={path} className="flex flex-col mb-1">
                  <div 
                    className={`flex items-center gap-1.5 px-2 py-1 cursor-pointer select-none group w-full overflow-hidden ${isDark ? 'hover:bg-zinc-800' : 'hover:bg-zinc-200'}`}
                    onClick={() => handleResultClick(path)}
                  >
                    <ChevronDown size={14} className="shrink-0 text-zinc-500" />
                    <File size={14} className="shrink-0 text-blue-400" />
                    <span className="text-xs truncate min-w-0 font-medium" title={path}>{fileName}</span>
                    <span className="text-[10px] text-zinc-500 bg-zinc-800/50 px-1 rounded-full shrink-0">{pathResults.length}</span>
                  </div>
                  <div className="flex flex-col">
                    {pathResults.map((res, i) => (
                      <div 
                        key={i} 
                        className={`flex items-start gap-2 pl-8 pr-2 py-0.5 cursor-pointer text-xs group ${isDark ? 'hover:bg-zinc-800/70 text-zinc-400' : 'hover:bg-zinc-200/70 text-zinc-600'}`}
                        onClick={() => handleResultClick(path)}
                        title={res.text.trim()}
                      >
                        <span className="shrink-0 w-8 text-right text-zinc-500 select-none opacity-50">{res.line}</span>
                        <span className="truncate flex-1 group-hover:text-zinc-200 font-mono text-[11px] mt-[1px]">
                          {renderHighlightedText(res.text.trim(), searchQuery)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        ) : searchQuery.length > 0 ? (
          <div className="px-6 text-xs text-zinc-500">No results found.</div>
        ) : (
          <div className="px-6 text-xs text-zinc-500">Type to search across workspace.</div>
        )}
      </div>
    </div>
  );
}
