// src/lib/components/panels/TitleMenuBar.svelte
<script lang="ts">
  import { editorStore } from '../../stores/editor';
  import { uiStore } from '../../stores/ui';
    import { getCurrentWindow } from '@tauri-apps/api/window';
  import { open, save } from '@tauri-apps/plugin-dialog';
  import { invoke } from '@tauri-apps/api/core';
  import { getHumanReadableError } from '../../utils/error';
  import { terminalStore } from '../../stores/terminal';

  const tabs = editorStore.tabs;
  const activeTabId = editorStore.activeTabId;
  const ui = uiStore;

  let activeTab = $derived($tabs.find(t => t.id === $activeTabId) || null);
  let isFileActive = $derived(!!activeTab);

  let openMenu = $state<string | null>(null);

  function handleNewTextFile() {
    let count = 1;
    const tabsSnapshot = editorStore.getTabsSnapshot();
    while (tabsSnapshot.some((t: any) => t.path === `Untitled-${count}`)) count++;
    const name = `Untitled-${count}`;
    const id = `tab-${Date.now()}`;
    editorStore.addTab({ id, path: name, name, content: '', language: 'plaintext', isPreview: false });
    editorStore.setActiveTab(id);
    closeAll();
  }

  async function handleNewWindow() { 
    try {
      await invoke('open_new_window');
      closeAll();
    } catch (e) {
      console.error('Failed to open new window', e);
    }
  }

  async function handleOpenFile() {
    try {
      const selected = await open({ multiple: false });
      if (selected && typeof selected === 'string') {
        const fileName = selected.split(/[/\\]/).pop() || 'Unknown';
        let content = '';
        const isImage = /\.(png|jpe?g|gif|webp|svg|ico)$/i.test(fileName);
        let isLargeFile = false;
        let isPreview = false;
        if (!isImage) {
          try {
            content = await invoke<string>('read_file_text', { path: selected });
          } catch (e) {
            if (String(e) === '__BINARY__') content = '';
            else if (String(e) === '__LARGE_FILE__') {
              const chunked = await invoke<any>('read_file_chunked', { path: selected });
              content = chunked.content;
              isLargeFile = true;
              isPreview = true;
            } else throw e;
          }
        }
        editorStore.addTab({
          id: `tab-${Date.now()}`, path: selected, name: fileName, content,
          language: isImage ? 'image' : await invoke<string>('detect_language', { path: selected }),
          isPreview,
          isLargeFile
        });
      }
    } catch (err) { console.error(err); }
    closeAll();
  }

  async function handleOpenFolder() {
    try {
      const selected = await open({ directory: true, multiple: false });
      if (selected && typeof selected === 'string') {
        if (selected === uiStore.getSnapshot().explorerRoot) {
          closeAll();
          return;
        }
        if (!$ui.recentWorkspaces.includes(selected)) {
          uiStore.setPendingTrustPath(selected);
        } else {
          window.dispatchEvent(new CustomEvent('request-workspace-switch', { detail: { path: selected } }));
        }
      }
    } catch (err) { console.error("Failed to open folder:", err); }
    closeAll();
  }

  async function handleSave() {
    if (!activeTab) return;
    if (activeTab.path.startsWith('Untitled')) {
      const selected = await save();
      if (selected && typeof selected === 'string') {
        const fileName = selected.split(/[/\\]/).pop() || 'Unknown';
        try {
          await invoke('save_file', { path: selected, content: activeTab.content });
          editorStore.closeTab(activeTab.id);
          editorStore.addTab({ ...activeTab, id: selected, path: selected, name: fileName });
        } catch (err) {
          console.error(err);
          uiStore.addToast('Save Failed', 'alert', getHumanReadableError(err));
        }
      }
    } else {
      try {
        await invoke('save_file', { path: activeTab.path, content: activeTab.content });
        editorStore.markSaved(activeTab.id);
        uiStore.addToast('Saved manually', 'success');
      } catch (err) {
        console.error(err);
        uiStore.addToast('Save Failed', 'alert', getHumanReadableError(err));
      }
    }
    closeAll();
  }

  async function handleSaveAs() {
    if (!activeTab) return;
    const selected = await save();
    if (selected && typeof selected === 'string') {
      try {
        await invoke('save_file', { path: selected, content: activeTab.content });
        const fileName = selected.split(/[/\\]/).pop() || 'Unknown';
        editorStore.closeTab(activeTab.id);
        editorStore.addTab({ ...activeTab, id: `tab-${Date.now()}`, path: selected, name: fileName });
        uiStore.addToast('Saved manually', 'success');
      } catch (err) {
        console.error(err);
        uiStore.addToast('Save Failed', 'alert', getHumanReadableError(err));
      }
    }
    closeAll();
  }

  function handleExit() { getCurrentWindow().close(); }

  function openSearch() { uiStore.setActiveSidebarPanel('search'); uiStore.setSidebarOpen(true); closeAll(); }
  function openExplorer() { uiStore.setActiveSidebarPanel('explorer'); uiStore.setSidebarOpen(true); closeAll(); }

  function dispatchEditorAction(action: string) {
    window.dispatchEvent(new CustomEvent('editor:action', { detail: { action } }));
    closeAll();
  }

  function closeAll() { openMenu = null; }

  $effect(() => {
    const onSave = () => handleSave();
    const onSaveAs = () => handleSaveAs();
    window.addEventListener('editor:save', onSave);
    window.addEventListener('editor:save-as', onSaveAs);
    return () => {
      window.removeEventListener('editor:save', onSave);
      window.removeEventListener('editor:save-as', onSaveAs);
    };
  });

  function toggleMenu(name: string) {
    openMenu = openMenu === name ? null : name;
  }

  function isDisabled() { return !isFileActive; }
  function isMinimapChecked() { return $ui.isMinimapEnabled; }

  const menus = [
    {
      label: 'File', items: [
        { label: 'New Text File', action: handleNewTextFile },
        { label: 'New File', action: () => { uiStore.openNewFileDialog('menu'); closeAll(); }, shortcut: 'Ctrl+N' },
        { label: 'New Window', action: handleNewWindow, sep: true, shortcut: 'Ctrl+Shift+N' },
        { label: 'Open File', action: handleOpenFile, shortcut: 'Ctrl+O' },
        { label: 'Open Folder', action: handleOpenFolder },
        { label: 'Open Recent...', action: () => { uiStore.openRecentFoldersModal(); closeAll(); }, sep: true },
        { label: 'Save', action: handleSave, disabled: isDisabled, shortcut: 'Ctrl+S' },
        { label: 'Save As', action: handleSaveAs, disabled: isDisabled, sep: true, shortcut: 'Ctrl+Shift+S' },
        { label: 'Exit', action: handleExit }
      ]
    },
    {
      label: 'Edit', items: [
        { label: 'Undo', action: () => dispatchEditorAction('undo'), disabled: isDisabled, shortcut: 'Ctrl+Z' },
        { label: 'Redo', action: () => dispatchEditorAction('redo'), disabled: isDisabled, sep: true, shortcut: 'Ctrl+Y' },
        { label: 'Cut', action: () => document.execCommand('cut'), shortcut: 'Ctrl+X' },
        { label: 'Copy', action: () => document.execCommand('copy'), shortcut: 'Ctrl+C' },
        { label: 'Paste', action: () => document.execCommand('paste'), sep: true, shortcut: 'Ctrl+V' },
        { label: 'Find', action: () => dispatchEditorAction('find'), disabled: isDisabled, shortcut: 'Ctrl+F' },
        { label: 'Replace', action: () => dispatchEditorAction('replace'), disabled: isDisabled, sep: true, shortcut: 'Ctrl+H' },
        { label: 'Reopen Closed Tab', action: () => editorStore.reopenClosedTab(), sep: true, shortcut: 'Ctrl+Shift+T' },
        { label: 'Find in Files', action: openSearch, shortcut: 'Ctrl+Shift+F' },
        { label: 'Replace in Files', action: openSearch, shortcut: 'Ctrl+Shift+H' }
      ]
    },
    {
      label: 'Selection', items: [
        { label: 'Select All', action: () => dispatchEditorAction('selectAll'), disabled: isDisabled, sep: true, shortcut: 'Ctrl+A' },
        { label: 'Copy Line Up', action: () => dispatchEditorAction('copyLineUp'), disabled: isDisabled, shortcut: 'Shift+Alt+Up' },
        { label: 'Copy Line Down', action: () => dispatchEditorAction('copyLineDown'), disabled: isDisabled, shortcut: 'Shift+Alt+Down' },
        { label: 'Move Line Up', action: () => dispatchEditorAction('moveLineUp'), disabled: isDisabled, shortcut: 'Alt+Up' },
        { label: 'Move Line Down', action: () => dispatchEditorAction('moveLineDown'), disabled: isDisabled, sep: true, shortcut: 'Alt+Down' },
        { label: 'Duplicate Selection', action: () => dispatchEditorAction('copyLineDown'), disabled: isDisabled }
      ]
    },
    {
      label: 'Terminal', items: [
        { 
          label: 'Open Terminal', 
          disabled: () => $terminalStore.terminals.length === 0 || $terminalStore.isVisible,
          shortcut: 'Ctrl+`',
          action: () => { 
            terminalStore.setVisibility(true); 
            closeAll(); 
          } 
        },
        { label: 'New Terminal', shortcut: 'Ctrl+Shift+`', action: () => { 
            const cwd = uiStore.getSnapshot().explorerRoot || '';
            terminalStore.newTerminal(undefined, cwd); 
            closeAll(); 
          } 
        }
      ]
    },
    {
      label: 'View', items: [
        { label: 'Command Palette', action: () => { window.dispatchEvent(new CustomEvent('open-command-palette')); closeAll(); }, sep: true, shortcut: 'Ctrl+Shift+P' },
        { label: 'Explorer', action: openExplorer, shortcut: 'Ctrl+Shift+E' },
        { label: 'Search', action: openSearch, shortcut: 'Ctrl+Shift+F' },
        { label: 'Smart Search', action: () => { window.dispatchEvent(new CustomEvent('open-smart-search')); closeAll(); }, sep: true, shortcut: 'Ctrl+P' },
        { label: 'Terminal', action: () => {
            if ($terminalStore.terminals.length === 0) {
              const cwd = uiStore.getSnapshot().explorerRoot || '';
              terminalStore.newTerminal(undefined, cwd);
            }
            terminalStore.setActivePanel('terminal');
            closeAll();
          }, shortcut: 'Ctrl+`'
        },
        { label: 'Problems', action: () => {
            terminalStore.setActivePanel('problems');
            closeAll();
          }
        },
        { label: 'Output', action: () => {
            terminalStore.setActivePanel('output');
            closeAll();
          }, sep: true
        },
        { label: 'Welcome Page', action: () => {
            const w = $tabs.find((t: any) => t.language === 'welcome');
            if (w) editorStore.setActiveTab(w.id);
            else editorStore.addTab({ id: 'welcome', path: 'Welcome', name: 'Welcome', content: '', language: 'welcome', isPreview: true });
            closeAll();
          }, checked: () => $tabs.some((t: any) => t.language === 'welcome') },
        { label: 'Minimap', action: () => { uiStore.toggleMinimap(); closeAll(); }, checked: isMinimapChecked }
      ]
    }
  ];
</script>

<svelte:window onclick={closeAll} />

<div class="flex items-center text-xs h-full ml-2 space-x-1">
  {#each menus as menu (menu.label)}
    <div class="relative">
      <button
        class="px-2 py-1 rounded outline-none cursor-pointer select-none transition-colors hover:bg-hover hover:text-primary"
        class:bg-selected={openMenu === menu.label}
        class:text-primary={openMenu === menu.label}
        onclick={(e) => { e.stopPropagation(); toggleMenu(menu.label); }}
      >
        {menu.label}
      </button>

      {#if openMenu === menu.label}
        <div
          role="menu"
          tabindex="0"
          class="absolute top-full left-0 min-w-[240px] rounded border shadow-elevated z-[100] py-1 bg-surface-2 border-subtle text-primary"
          onclick={(e) => { e.stopPropagation(); closeAll(); }}
          onkeydown={(e) => { if (e.key === 'Escape') closeAll(); }}
        >
          {#each menu.items as item (item.label)}
              <button
                class="flex items-center justify-between w-full px-3 py-1.5 text-xs outline-none cursor-pointer select-none {!(item as any).disabled?.() ? 'hover:bg-selected focus:bg-selected text-secondary hover:text-primary transition-colors' : 'text-muted'}"
                disabled={(item as any).disabled?.()}
                onclick={() => { if (!((item as any).disabled?.())) { (item as any).action(); } }}
                onmouseenter={(e) => (e.target as HTMLElement).focus()}
              >
                <div class="flex items-center">
                  <div class="w-4 mr-2 flex justify-center items-center">
                    {#if (item as any).checked?.()}<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>{/if}
                  </div>
                  {(item as any).label}
                </div>
                {#if (item as any).shortcut}
                  <span class="ml-4 text-[10px] text-muted opacity-80">{(item as any).shortcut}</span>
                {/if}
              </button>
            {#if (item as any).sep}
              <div class="h-px my-1 bg-subtle"></div>
            {/if}
          {/each}
        </div>
      {/if}
    </div>
  {/each}
</div>

// src/components/TitleMenuBar.tsx
import { useEffect } from 'react';
import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import { useSettingsStore } from '../store/settingsStore';
import { useEditorStore } from '../store/editorStore';
import { useUiStore } from '../store/uiStore';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { open, save } from '@tauri-apps/plugin-dialog';
import { invoke } from '@tauri-apps/api/core';
import { Check } from 'lucide-react';

export function TitleMenuBar() {
  const isDark = useSettingsStore(state => state.settings.theme === 'dark' || (state.settings.theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches));
  const { tabs, activeTabId, addTab, closeTab, markSaved } = useEditorStore();
  const { setExplorerRoot, setActiveSidebarPanel, setSidebarOpen, openNewFileDialog, isMinimapEnabled, toggleMinimap } = useUiStore();

  const activeTab = tabs.find(t => t.id === activeTabId);
  const isFileActive = !!activeTab;

  const handleNewTextFile = () => {
    let count = 1;
    while (tabs.some(t => t.path === `Untitled-${count}`)) {
      count++;
    }

    addTab({
      id: `tab-${Date.now()}`,
      path: `Untitled-${count}`,
      name: `Untitled-${count}`,
      content: '',
      language: 'plaintext'
    });
  };

  const handleNewWindow = () => {
    // Open new instance of the app, handled via rust or a simple command if set up.
    // Given Tauri context, we can just dispatch an IPC to create window, 
    // but standard way is `WebviewWindow` if imported. For now just placeholder or alert if not implemented.
    alert("New Window is not implemented yet");
  };

  const handleOpenFile = async () => {
    try {
      const selected = await open({ multiple: false });
      if (selected && typeof selected === 'string') {
        const fileName = selected.split(/[/\\]/).pop() || 'Unknown';
        let content = '';
        const isImage = /\.(png|jpe?g|gif|webp|svg|ico)$/i.test(fileName);
        if (!isImage) {
          const bytes = await invoke<number[]>('read_file_binary', { path: selected });
          content = new TextDecoder('utf-8').decode(new Uint8Array(bytes)).replace(/\r\n/g, '\n');
        }
        addTab({
          id: `tab-${Date.now()}`,
          path: selected,
          name: fileName,
          content: content,
          language: isImage ? 'image' : await invoke<string>('detect_language', { path: selected }),
          isPreview: false
        });
      }
    } catch (err) {
      console.error(err);
    }
  };

  const handleOpenFolder = async () => {
    try {
      const selected = await open({ directory: true, multiple: false });
      if (selected && typeof selected === 'string') {
        setExplorerRoot(selected);
      }
    } catch (err) {
      console.error(err);
    }
  };

  const handleSave = async () => {
    if (!activeTab) return;
    if (activeTab.path.startsWith('Untitled')) {
      const selected = await save();
      if (selected && typeof selected === 'string') {
        const fileName = selected.split(/[/\\]/).pop() || 'Unknown';
        try {
          await invoke('save_file', { path: selected, content: activeTab.content });
          // We need to update tab path! Since addTab creates a new one or updates existing if path matches.
          // Better yet, update it in the store directly, but for now we can just close old and open new,
          // or rely on markSaved and changing the id manually, but editorStore doesn't expose renameTab.
          // For simplicity:
          closeTab(activeTab.id);
          addTab({
            ...activeTab,
            id: selected,
            path: selected,
            name: fileName
          });
          // Since addTab does not support isModified initialization, we just assume it's saved.
          // Wait, isModified is maintained automatically? 
          // Actually markSaved should be used after addTab if needed.
        } catch (err) {
          console.error(err);
        }
      }
    } else {
      try {
        await invoke('save_file', { path: activeTab.path, content: activeTab.content });
        markSaved(activeTab.id);
      } catch (err) {
        console.error(err);
      }
    }
  };

  const handleSaveAs = async () => {
    if (!activeTab) return;
    const selected = await save();
    if (selected && typeof selected === 'string') {
      try {
        await invoke('save_file', { path: selected, content: activeTab.content });
        const fileName = selected.split(/[/\\]/).pop() || 'Unknown';
        closeTab(activeTab.id);
        addTab({
          ...activeTab,
          id: `tab-${Date.now()}`,
          path: selected,
          name: fileName,
        });
        // We shouldn't need to manually mark saved since addTab sets isModified to false!
      } catch (err) {
        console.error(err);
      }
    }
  };

  useEffect(() => {
    const onSave = () => handleSave();
    const onSaveAs = () => handleSaveAs();
    window.addEventListener('editor:save', onSave);
    window.addEventListener('editor:save-as', onSaveAs);
    return () => {
      window.removeEventListener('editor:save', onSave);
      window.removeEventListener('editor:save-as', onSaveAs);
    };
  }, [handleSave, handleSaveAs]);

  const handleExit = () => {
    getCurrentWindow().close();
  };

  const openSearch = () => {
    setActiveSidebarPanel('search');
    setSidebarOpen(true);
  };

  const openExplorer = () => {
    setActiveSidebarPanel('explorer');
    setSidebarOpen(true);
  };

  const dispatchEditorAction = (action: string) => {
    window.dispatchEvent(new CustomEvent('editor:action', { detail: { action } }));
  };

  const menus = [
    {
      label: 'File',
      items: [
        { label: 'New Text File', action: handleNewTextFile },
        { label: 'New File', action: () => openNewFileDialog('menu') },
        { label: 'New Window', action: handleNewWindow },
        { separator: true },
        { label: 'Open File', action: handleOpenFile },
        { label: 'Open Folder', action: handleOpenFolder },
        { separator: true },
        { label: 'Save', action: handleSave, disabled: !isFileActive },
        { label: 'Save As', action: handleSaveAs, disabled: !isFileActive },
        { separator: true },
        { label: 'Exit', action: handleExit }
      ]
    },
    {
      label: 'Edit',
      items: [
        { label: 'Undo', action: () => dispatchEditorAction('undo'), disabled: !isFileActive },
        { label: 'Redo', action: () => dispatchEditorAction('redo'), disabled: !isFileActive },
        { separator: true },
        { label: 'Cut', action: () => document.execCommand('cut') },
        { label: 'Copy', action: () => document.execCommand('copy') },
        { label: 'Paste', action: () => document.execCommand('paste') },
        { separator: true },
        { label: 'Find', action: () => dispatchEditorAction('find'), disabled: !isFileActive },
        { label: 'Replace', action: () => dispatchEditorAction('replace'), disabled: !isFileActive },
        { separator: true },
        { label: 'Find in Files', action: openSearch },
        { label: 'Replace in Files', action: openSearch }
      ]
    },
    {
      label: 'Selection',
      items: [
        { label: 'Select All', action: () => dispatchEditorAction('selectAll'), disabled: !isFileActive },
        { separator: true },
        { label: 'Copy Line Up', action: () => dispatchEditorAction('copyLineUp'), disabled: !isFileActive },
        { label: 'Copy Line Down', action: () => dispatchEditorAction('copyLineDown'), disabled: !isFileActive },
        { label: 'Move Line Up', action: () => dispatchEditorAction('moveLineUp'), disabled: !isFileActive },
        { label: 'Move Line Down', action: () => dispatchEditorAction('moveLineDown'), disabled: !isFileActive },
        { separator: true },
        { label: 'Duplicate Selection', action: () => dispatchEditorAction('copyLineDown'), disabled: !isFileActive } // Duplicate selection translates to copyLineDown in cm6 for simplest mapping
      ]
    },
    {
      label: 'View',
      items: [
        { label: 'Explorer', action: openExplorer },
        { label: 'Search', action: openSearch },
        { separator: true },
        { label: 'Minimap', action: toggleMinimap, checked: isMinimapEnabled }
      ]
    }
  ];

  return (
    <div className="flex items-center text-xs h-full ml-2 space-x-1">
      {menus.map((menu, i) => (
        <DropdownMenu.Root key={i}>
          <DropdownMenu.Trigger className={`px-2 py-1 rounded outline-none cursor-default select-none transition-colors ${isDark ? 'hover:bg-zinc-700 data-[state=open]:bg-zinc-700' : 'hover:bg-zinc-300 data-[state=open]:bg-zinc-300'}`}>
            {menu.label}
          </DropdownMenu.Trigger>
          <DropdownMenu.Portal>
            <DropdownMenu.Content 
              align="start"
              sideOffset={4}
              className={`min-w-[200px] rounded border shadow-lg z-[100] py-1 ${isDark ? 'bg-[#1e1e1e] border-zinc-800 text-zinc-300' : 'bg-white border-zinc-200 text-zinc-800'}`}
            >
              {menu.items.map((item, j) => {
                const menu_item: any = item;
                if (menu_item.separator) {
                  return <DropdownMenu.Separator key={j} className={`h-px my-1 ${isDark ? 'bg-zinc-800' : 'bg-zinc-200'}`} />;
                }
                return (
                  <DropdownMenu.Item
                    key={j}
                    disabled={menu_item.disabled}
                    onSelect={(e) => {
                      if (menu_item.checked !== undefined) {
                        e.preventDefault(); // Don't close menu immediately for checkboxes if desired, but we'll let it close for now.
                      }
                      menu_item.action();
                    }}
                    className={`px-3 py-1.5 text-xs outline-none cursor-default select-none flex items-center ${menu_item.disabled ? 'opacity-50' : (isDark ? 'focus:bg-blue-600 focus:text-white' : 'focus:bg-blue-500 focus:text-white')}`}
                  >
                    <div className="w-4 mr-2 flex justify-center items-center">
                      {menu_item.checked && <Check size={14} />}
                    </div>
                    {menu_item.label}
                  </DropdownMenu.Item>
                );
              })}
            </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>
      ))}
    </div>
  );
}
